# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - GBPUSDpredictordocker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://testdockertee.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_e352e4e86f2646ddad4bb67f3da79604 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8e6090ffebf74042bd5ff898859c26a6 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: testdockertee.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e352e4e86f2646ddad4bb67f3da79604 }}/testdockertee/gbpusdpredictor:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'GBPUSDpredictordocker'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_8e1636501ea34efb8dba67d8dfd922ce }}
        images: 'testdockertee.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e352e4e86f2646ddad4bb67f3da79604 }}/testdockertee/gbpusdpredictor:${{ github.sha }}'